### PR TITLE
Improved Footer

### LINKED ISSUE #27: Improve footer bar
Footer bar could be improved
**Screenshots**
Screenshot 2022-10-12 at 10 09 52 PM

### PR DESCRIPTION
**Pull request by asdsyd**
'Closes #27'

## Screenshots
Before:
Screenshot 2022-10-13 at 12 44 26 PM

After:
Screenshot 2022-10-13 at 12 44 07 PM

### CODE REVIEW

**Comment by RakeshSangem** [comment]
Hello, @asdsyd. I like the changes, and I am thinking to remove the Navigation links from the footer. Could you pull it off?

**Comment by asdsyd** [comment]
Alright.

**Comment by asdsyd** [comment]
@RakeshSangem done.
Before:
Screenshot 2022-10-13 at 1 21 20 PM

After:
Screenshot 2022-10-13 at 1 20 59 PM

**Comment by RakeshSangem** [comment]
I believe you also need to remove the CSS code which is related to think links.

**Comment by asdsyd** [comment]
Have a look.

**Review by RakeshSangem — APPROVED** [review]
Looks good to me @asdsyd, thanks for your contribution💙

**Pull request merged**
