### PR TITLE
Hover effects navbar

### LINKED ISSUE #7: [FEATURE] add hover effects to navigation links
### Is your feature request related to a problem? Please describe.**
currently, we don't have any hover state for navigation links. It looks good when we have hover state in Desktop.

### PR DESCRIPTION
**Pull request by dhruvdabhi101**
## Fixes Issue

Closes #7 

## Changes proposed

Added Hover Effect in Navbar

## Screenshots

Screenshot 2022-09-25 at 10 02 43 PM

## Note to reviewers

- Please check the code and Suggest changes.

### CODE REVIEW

**Comment by RakeshSangem** [comment]
Hey @dhruvdabhi101, Could you please just go with the normal font color change? I just wanted simple and cleaner version.

**Comment by dhruvdabhi101** [comment]
> Hey @dhruvdabhi101, Could you please just go with the normal font color change? I just wanted simple and cleaner version.

Okay sir.. Understood. :)

**Comment by RakeshSangem** [comment]
> Okay sir.. Understood. :)

Thank you:)

**Comment by dhruvdabhi101** [comment]
check out the changes.. and tell if something is wrong. ☺️

**Comment by RakeshSangem** [comment]
> check out the changes.. and tell if something is wrong. ☺️

Satisfied with the changes, thank you so much for contributing❤

**Review by RakeshSangem — APPROVED** [review]
LGTM🎉

**Pull request merged**
