### PR TITLE
dark mode

### LINKED ISSUE #10: [FEATURE] add functionality to dark/light mode icon
Add functionality to dark/light mode icon.
- create CSS root variables

### Note: please use prettier to format the cod before you create PR

reference image
Screenshot 2022-09-30 235914

### PR DESCRIPTION
**Pull request by NisooJadhav**
## Fixed Issue
Dark Mode logic.

## Video
[screen-recording.webm](https://user-images.githubusercontent.com/68807845/193394350-66d6a6d9-1374-4bb8-8a1c-86f7352e67f1.webm)

## Live: [Portfolio](https://portfolio-eta.vercel.app/)

### CODE REVIEW

**Review by RakeshSangem — APPROVED** [review]
Looks good to me.

Thanks for contributing 💙

**Comment by NisooJadhav** [comment]
latest commits resulted in failure of dark mode working and card: hover -> drop shadow. My :root CSS is also removed.

**Comment by RakeshSangem** [comment]
Hey @NisooJadhav, Sorry about that:(

If you want to do it again, you can create an issue and work on it.

**Comment by NisooJadhav** [comment]
> Hey @NisooJadhav, Sorry about that:(
> 
> If you want to do it again, you can create an issue and work on it.

I will merge the animation feature on my local version if it will work locally will open a PR. Is this okay?

**Comment by RakeshSangem** [comment]
> > Hey @NisooJadhav, Sorry about that:(
> > If you want to do it again, you can create an issue and work on it.
> 
> I will merge the animation feature on my local version if it will work locally will open a PR. Is this okay?

Sure, it works too:)

**Comment by RakeshSangem** [comment]
Hey @NisooJadhav are you working on it? Or else I thinking to create an issue so that others will contribute.

Thanks:)

**Comment by NisooJadhav** [comment]
> Hey @NisooJadhav are you working on it? Or else I am thinking to create an issue so that others will contribute.
> 
> Thanks:)

this repo contains dark mode https://github.com/NisooJadhav/portfolio, animation is needed to add to it, our exams are going on I will be available after 4-5 days. Sorry :(

**Pull request merged**
