### PR TITLE
Centered Footer, icons, anchor tags, favicon, minor changes

### LINKED ISSUE #31: [BUG] Dark mode doesn't work
**Describe the bug**
Dark mode toggle doesnt work when clicked.
Please implement dark mode.
**To Reproduce**
Click on dark mode button in top right corner.
**Expected behavior**
toggles to dark mode
**Screenshots**
Screenshot 2022-10-13 at 12 47 39 PM

### PR DESCRIPTION
**Pull request by NisooJadhav**

### CODE REVIEW

**Comment by NisooJadhav** [comment]
> Hey @NisooJadhav , Thanks for making changes/additions. But I found some issues.
> 
> 1. It would be great if you use semantics HTML tags for i.e. `<footer>`
> 2. Footer Conflicts with the project card as shown in the picture.
> mobile view
> 

sorry for that issue, will do it by tomorrow

**Comment by RakeshSangem** [comment]
> sorry for that issue, will do it by tomorrow

no worries, Thank you:)

**Comment by NisooJadhav** [comment]
Added Semantic HTML Tag Footer, resolved footer conflict on mobile screens:
final

Output: [portfolio](https://portfolio-eta.vercel.app/)

**Review by RakeshSangem — APPROVED** [review]
LGTM🎉

**Pull request merged**
