### PR TITLE
Added @media query so the website is responsive

### PR DESCRIPTION
**Pull request by abitsalihu**
## Screenshots

Below are videos of how the website will look across different views:

Desktop View:

https://user-images.githubusercontent.com/94648837/192097511-51f7fa87-f903-405c-b4f7-784e977e7d07.mov

Tablet View:

https://user-images.githubusercontent.com/94648837/192097521-5d7990bd-a1e3-4ae5-9e74-2ea0bad81ae8.mov

Mobile View:

https://user-images.githubusercontent.com/94648837/192097526-443fcf3e-cf2f-4351-881e-465b63695021.mov

### CODE REVIEW

**Comment by RakeshSangem** [comment]
If you can make this changes, that would be great!

- In mobile view fix the `freelancer` and `open source contributor` titles alignment.
- hide navLinks in movie view only show `github` and `twitter`

**Comment by abitsalihu** [comment]
@RakeshSangem That's not a problem, I'll fix  the `freelancer` and `open source contributor` part, so on mobile view you don't want the link and the toggle button, just the `github` and `twitter` buttons? Also should I put them side by side with the logo in mobile view since there is space or do you wish to keep them in a column layout?

**Comment by RakeshSangem** [comment]
> @RakeshSangem That's not a problem, I'll fix the `freelancer` and `open source contributor` part, so on mobile view you don't want the link and the toggle button, just the `github` and `twitter` buttons? Also should I put them side by side with the logo in mobile view since there is space or do you wish to keep them in a column layout?

Yeah, In mobile view we don't need navigation links as it is single page website. And the `GitHub` and `Twitter` icons should be in row only.

**Comment by abitsalihu** [comment]
Fixed the `description` alignment issues and removed the `links` on mobile view, I left the toggle switch as it seemed an important button for the `user`

New look on `mobile view`:

https://user-images.githubusercontent.com/94648837/192098483-5de4fd2d-ea37-4f45-b63d-a7d9af91cd6c.mov

**Comment by RakeshSangem** [comment]
Looks good to me. Thanks for contributing❤

**Comment by abitsalihu** [comment]
@RakeshSangem Thanks for letting me. :)

**Pull request merged**
