### PR TITLE
Just added some animations and added a logo transparent

### PR DESCRIPTION
**Pull request by AliReza1083**
My project is done.
Just taste the small of it, there will be new things in the future.

### CODE REVIEW

**Comment by RakeshSangem** [comment]
It would be great if Can you change project card animation to bottom to up?

**Comment by AliReza1083** [comment]
Sure Will do it

**Comment by AliReza1083** [comment]
Done @RakeshSangem

**Comment by AliReza1083** [comment]
Thanks Rakesh

**Comment by RakeshSangem** [comment]
> Thanks Rakesh

No worries 😇

**Pull request merged**
