### PR TITLE
Add skill section

### PR DESCRIPTION
**Pull request by coder-chahal**
## Screenshots

skill

### CODE REVIEW

**Comment by RakeshSangem** [comment]
Could you please fix alignment issues? And the colors which you have chosen are not pleasing to eyes.

**Comment by coder-chahal** [comment]
Yaa sure :)

**Comment by coder-chahal** [comment]
Desktop preview
ss

Mobile preview
ss1

**Comment by coder-chahal** [comment]
commit changes merge PR with level:)

**Review by zelfroster — APPROVED** [review]
Good Job, should have given some space from the sides for a better look.
LGTM

**Review by RakeshSangem — APPROVED** [review]
Looks good to me🎉

Thanks for your contribution:)

**Pull request merged**
